//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegUsuario
    {
        public int IdUsuario { get; set; }
        public string CodUsuario { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Atributo1 { get; set; }
        public string Atributo2 { get; set; }
        public string Atributo3 { get; set; }
        public string Atributo4 { get; set; }
        public string Atributo5 { get; set; }
        public string Atributo6 { get; set; }
        public string Atributo7 { get; set; }
        public string Atributo8 { get; set; }
        public string Atributo9 { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<System.DateTime> FechaBloqueado { get; set; }
        public Nullable<System.DateTime> FechaVtoPassword { get; set; }
        public string TipoUsuario { get; set; }
    }
}
